//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodDonationProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int PostID { get; set; }
        public int UserId { get; set; }
        public string Address { get; set; }
        public string WantedBlood { get; set; }
        public string Text { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual Post Posts1 { get; set; }
        public virtual Post Post1 { get; set; }
        public virtual userInfo userInfo { get; set; }
    }
}
